Status =
    OMOTE: 0
    QUEEN: 1
    BISHOP: 2
    KNIGHT: 3
    ROOK: 4
    MOTIGOMA: 9

FIRST = -1
SECOND = 1
COLS = 8
ROWS = 8
MAX_VALUE = 50000
MIN_VALUE = -50000
STALEMATE_VALUE = -0.0009
STALEMATE = -30000
CHECKMATE = 30000
KING_CASTLING = 0
QUEEN_CASTLING = 1

# 7 x 3
KIFU_ROW_LENGTH = 21
# 7 x 3 行末スペースが削られてるケース
KIFU_ROW_LENGTH_SUB = 20
KIFU_KOMA_LENGTH = 3
TEMP_HISTORY = 'history.json'
TEMP_DUPLICATION = 'duplication.json'
LOADING_MESSAGE = 'Loading...'

module.exports =
    Status: Status
    FIRST: FIRST
    SECOND: SECOND
    COLS: COLS
    ROWS: ROWS
    STALEMATE_VALUE: STALEMATE_VALUE
    STALEMATE: STALEMATE
    CHECKMATE: CHECKMATE
    KING_CASTLING: KING_CASTLING
    QUEEN_CASTLING: QUEEN_CASTLING
    MAX_VALUE: MAX_VALUE
    MIN_VALUE: MIN_VALUE
    KIFU_ROW_LENGTH: KIFU_ROW_LENGTH
    KIFU_ROW_LENGTH_SUB: KIFU_ROW_LENGTH_SUB
    KIFU_KOMA_LENGTH: KIFU_KOMA_LENGTH
    TEMP_HISTORY: TEMP_HISTORY
    TEMP_DUPLICATION: TEMP_DUPLICATION
    LOADING_MESSAGE: LOADING_MESSAGE
